export const SUBMIT_USER = 'SUBMIT_USER';
export const SUBMIT_USER_FULFILLED = 'SUBMIT_USER_FULFILLED';
export const SUBMIT_USER_PENDING = 'SUBMIT_USER_PENDING';
export const SUBMIT_USER_REJECTED = 'SUBMIT_USER_REJECTED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const ADD_BUDGET = 'ADD_BUDGET';
export const ADD_BUDGET_FULFILLED = 'ADD_BUDGET_FULFILLED';
export const ADD_BUDGET_PENDING = 'ADD_BUDGET_PENDING';
export const ADD_BUDGET_REJECTED = 'ADD_BUDGET_REJECTED';

export const GET_BUDGET = 'GET_BUDGET';
export const GET_BUDGET_FULFILLED = 'GET_BUDGET_FULFILLED';
export const GET_BUDGET_PENDING = 'GET_BUDGET_PENDING';
export const GET_BUDGET_REJECTED = 'GET_BUDGET_REJECTED';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_FULFILLED = 'ADD_CATEGORY_FULFILLED';
export const ADD_CATEGORY_PENDING = 'ADD_CATEGORY_PENDING';
export const ADD_CATEGORY_REJECTED = 'ADD_CATEGORY_REJECTED';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ADD_EXPENSE_FULFILLED = 'ADD_EXPENSE_FULFILLED';
export const ADD_EXPENSE_PENDING = 'ADD_EXPENSE_PENDING';
export const ADD_EXPENSE_REJECTED = 'ADD_EXPENSE_REJECTED';

export const GET_EXPENSE = 'GET_EXPENSE';
export const GET_EXPENSE_FULFILLED = 'GET_EXPENSE_FULFILLED';
export const GET_EXPENSE_PENDING = 'GET_EXPENSE_PENDING';
export const GET_EXPENSE_REJECTED = 'GET_EXPENSE_REJECTED';


export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const DELETE_EXPENSE_FULFILLED = 'DELETE_EXPENSE_FULFILLED';
export const DELETE_EXPENSE_PENDING = 'DELETE_EXPENSE_PENDING';
export const DELETE_EXPENSE_REJECTED = 'DELETE_EXPENSE_REJECTED';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_FULFILLED = 'DELETE_CATEGORY_FULFILLED';
export const DELETE_CATEGORY_PENDING = 'DELETE_CATEGORY_PENDING';
export const DELETE_CATEGORY_REJECTED = 'DELETE_CATEGORY_REJECTED';

export const GET_EXPESES_AND_DATE = 'GET_EXPESES_AND_DATE';
export const GET_EXPESES_AND_DATE_FULFILLED = 'GET_EXPESES_AND_DATE_FULFILLED';
export const GET_EXPESES_AND_DATE_PENDING = 'GET_EXPESES_AND_DATE_PENDING';
export const GET_EXPESES_AND_DATE_REJECTED = 'GET_EXPESES_AND_DATE_REJECTED';

export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';
export const GET_REFRESH_TOKEN_FULFILLED = 'GET_REFRESH_TOKEN_FULFILLED';
export const GET_REFRESH_TOKEN_PENDING = 'GET_REFRESH_TOKEN_PENDING';
export const GET_REFRESH_TOKEN_REJECTED = 'GET_REFRESH_TOKEN_REJECTED';